package validator
// Code generated by genclaims.go; DO NOT EDIT.

func (c Claims) Sub() string {
	_value, ok := c["sub"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Name() string {
	_value, ok := c["name"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) GivenName() string {
	_value, ok := c["given_name"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) FamilyName() string {
	_value, ok := c["family_name"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) MiddleName() string {
	_value, ok := c["middle_name"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Nickname() string {
	_value, ok := c["nickname"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) PreferredUsername() string {
	_value, ok := c["preferred_username"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Profile() string {
	_value, ok := c["profile"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Picture() string {
	_value, ok := c["picture"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Website() string {
	_value, ok := c["website"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Email() string {
	_value, ok := c["email"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Gender() string {
	_value, ok := c["gender"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Birthdate() string {
	_value, ok := c["birthdate"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Zoneinfo() string {
	_value, ok := c["zoneinfo"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) Locale() string {
	_value, ok := c["locale"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) PhoneNumber() string {
	_value, ok := c["phone_number"]
	if !ok {
		return ""
	}
	value, ok := _value.(string)
	if !ok {
		return ""
	}
	return value
}

func (c Claims) EmailVerified() bool {
	_value, ok := c["email_verified"]
	if !ok {
		return false
	}
	value, ok := _value.(bool)
	if !ok {
		return false
	}
	return value
}

func (c Claims) PhoneNumberVerified() bool {
	_value, ok := c["phone_number_verified"]
	if !ok {
		return false
	}
	value, ok := _value.(bool)
	if !ok {
		return false
	}
	return value
}

func (c Claims) UpdatedAt() float64 {
	_value, ok := c["updated_at"]
	if !ok {
		return 0
	}
	value, ok := _value.(float64)
	if !ok {
		return 0
	}
	return value
}

func (c Claims) Exp() float64 {
	_value, ok := c["exp"]
	if !ok {
		return 0
	}
	value, ok := _value.(float64)
	if !ok {
		return 0
	}
	return value
}
